<script setup>
import { computed, ref } from 'vue';
import { Link, useForm } from '@inertiajs/vue3';
import axios from 'axios';
import AppLayout from '../../../Layouts/AppLayout.vue';
import AccountNav from '../../../Components/AccountNav.vue';
import SeoHead from '../../../Components/SeoHead.vue';
import MoneyDisplay from '../../../Components/Public/UI/MoneyDisplay.vue';
import { appUrl } from '../../../appUrl';
import { useLocalization } from '../../../i18n';

const props = defineProps({ booking: { type: Object, required: true }, actions: { type: Object, required: true }, reasons: { type: Array, default: () => [] } });
const { t, locale } = useLocalization();
const endpoint = appUrl(`/account/taxi/changes/${props.booking.id}`);
const cancellationQuote = ref(null); const rescheduleQuote = ref(null); const error = ref(''); const previewing = ref(false);
const cancellationForm = useForm({ reason_code: 'customer_request', reason: '', confirmed: false });
const rescheduleForm = useForm({ pickup_at: '', return_at: '', reason: '', confirmed: false });

function date(value) { return value ? new Intl.DateTimeFormat(locale.value || 'en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
function label(value) { return t(`common.${value}`, String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())); }
function money(value) { return value || null; }
async function preview(kind) {
    previewing.value = true; error.value = '';
    try {
        if (kind === 'cancel') cancellationQuote.value = (await axios.get(`${endpoint}/quote`, { params: { no_show: 0 } })).data;
        else rescheduleQuote.value = (await axios.post(`${endpoint}/reschedule-quote`, rescheduleForm.data())).data;
    } catch (responseError) { error.value = Object.values(responseError.response?.data?.errors || {}).flat().join(' ') || t('common.preview_unavailable', 'This preview is no longer available. Refresh and try again.'); }
    finally { previewing.value = false; }
}

const priceRows = computed(() => Object.entries(props.booking.pricing?.breakdown || {}).filter(([, value]) => Number(value?.amount || 0) !== 0));
</script>

<template>
    <AppLayout><SeoHead :title="`${t('common.booking_details', 'Booking details')} · ${booking.reference}`" :noindex="true" private-page />
        <div class="public-container taxi-customer-shell"><AccountNav active="taxi" /><Link class="taxi-back-link" :href="appUrl('/account/taxi/bookings')">← {{ t('common.my_taxi_bookings', 'My Taxi Bookings') }}</Link>
            <header class="taxi-detail-header"><div><span class="public-eyebrow">{{ booking.reference }}</span><h1 class="public-heading public-heading--2">{{ t('common.taxi_booking_record', 'Taxi booking record') }}</h1><p>{{ date(booking.pickup_at) }} · {{ booking.pickup_address }} → {{ booking.drop_address }}</p></div><div class="taxi-status-pair taxi-status-pair--large"><b>{{ label(booking.status) }}</b><em>{{ label(booking.payment_status) }}</em></div></header>
            <div class="taxi-detail-layout"><main class="taxi-detail-main">
                <section class="taxi-detail-panel taxi-route-panel"><h2>{{ t('common.route_details', 'Route details') }}</h2><div class="taxi-detail-route"><div><small>{{ t('common.pickup', 'Pickup') }}</small><strong>{{ booking.pickup_address }}</strong><span>{{ date(booking.pickup_at) }}</span></div><i class="bi bi-arrow-down" aria-hidden="true"></i><div><small>{{ t('common.drop', 'Dropoff') }}</small><strong>{{ booking.drop_address }}</strong><span v-if="booking.return_at">{{ t('common.return_time', 'Return') }} · {{ date(booking.return_at) }}</span></div></div><div class="taxi-fact-grid"><div><small>{{ t('common.vehicle', 'Vehicle') }}</small><strong>{{ booking.vehicle?.name || '—' }}</strong></div><div><small>{{ t('common.passengers', 'Passengers') }}</small><strong>{{ booking.passenger_count }}</strong></div><div><small>{{ t('common.luggage', 'Luggage') }}</small><strong>{{ booking.luggage_count ?? '—' }}</strong></div><div><small>{{ t('common.trip_type', 'Trip type') }}</small><strong>{{ label(booking.trip_type) }}</strong></div></div><div v-if="booking.assigned_driver || booking.assigned_vehicle" class="taxi-assignment"><span>{{ t('common.assigned_ride_team', 'Assigned ride team') }}</span><strong>{{ booking.assigned_driver?.display_name || t('common.driver_pending', 'Driver assignment pending') }}</strong><small v-if="booking.assigned_vehicle">{{ booking.assigned_vehicle.name }}<span v-if="booking.assigned_vehicle.make_model"> · {{ booking.assigned_vehicle.make_model }}</span></small></div></section>
                <section class="taxi-detail-panel"><h2>{{ t('common.price_summary', 'Price summary') }}</h2><div class="taxi-money-list"><div v-for="[key, value] in priceRows" :key="key"><span>{{ label(key) }}</span><MoneyDisplay :money="money(value)" /></div><div class="taxi-money-list__total"><strong>{{ t('common.total', 'Total') }}</strong><MoneyDisplay :money="booking.pricing.total" /></div></div><div class="taxi-payment-grid"><div><small>{{ t('common.paid_so_far', 'Paid so far') }}</small><MoneyDisplay :money="booking.payment.paid" /></div><div><small>{{ t('common.outstanding_due', 'Outstanding due') }}</small><MoneyDisplay :money="booking.payment.due" /></div></div></section>
                <section class="taxi-detail-panel"><h2>{{ t('common.customer_details', 'Customer details') }}</h2><div class="taxi-customer-details"><div><small>{{ t('common.name', 'Name') }}</small><strong>{{ booking.customer.name }}</strong></div><div><small>{{ t('common.phone', 'Phone') }}</small><strong>{{ booking.customer.phone }}</strong></div><div v-if="booking.customer.email"><small>{{ t('common.email', 'Email') }}</small><strong>{{ booking.customer.email }}</strong></div></div><p v-if="booking.special_instructions" class="taxi-note">{{ booking.special_instructions }}</p></section>
                <section class="taxi-detail-panel"><h2>{{ t('common.booking_history', 'Booking history') }}</h2><div v-if="booking.history.length" class="taxi-timeline"><div v-for="item in booking.history" :key="`${item.to}-${item.at}`"><span></span><strong>{{ label(item.to) }}</strong><small>{{ date(item.at) }}</small></div></div><p v-else class="taxi-muted">{{ t('common.no_booking_history', 'No booking history is available yet.') }}</p><div v-if="booking.reschedules.length" class="taxi-history-note"><strong>{{ t('common.reschedule_history', 'Reschedule history') }}</strong><p v-for="change in booking.reschedules" :key="change.new_pickup_at">{{ date(change.old_pickup_at) }} → {{ date(change.new_pickup_at) }}<span v-if="change.reason"> · {{ change.reason }}</span></p></div></section>
                <section v-if="booking.cancellation || booking.refunds.length" class="taxi-detail-panel"><h2>{{ t('common.cancellation_refunds', 'Cancellation and refunds') }}</h2><div v-if="booking.cancellation" class="taxi-cancellation-record"><strong>{{ label(booking.cancellation.status) }}</strong><span>{{ t('common.cancellation_fee', 'Cancellation fee') }}: <MoneyDisplay :money="booking.cancellation.fee" /></span><span>{{ t('common.refundable_amount', 'Refundable amount') }}: <MoneyDisplay :money="booking.cancellation.refundable" /></span></div><div v-for="refund in booking.refunds" :key="refund.reference" class="taxi-refund-row"><span>{{ refund.reference }}</span><MoneyDisplay :money="refund.amount" /><em>{{ label(refund.status) }}</em></div><p class="taxi-muted">{{ t('common.taxi_refund_note', 'Refund records reflect operator settlement. This page does not transfer money.') }}</p></section>
                <section v-if="booking.review || actions.can_review" class="taxi-detail-panel"><h2>{{ t('common.taxi_review', 'Taxi review') }}</h2><div v-if="booking.review"><strong class="taxi-review-stars">{{ '★'.repeat(booking.review.overall_rating) }}{{ '☆'.repeat(5 - booking.review.overall_rating) }}</strong><span class="taxi-review-state">{{ label(booking.review.status) }}</span><p v-if="booking.review.comment">{{ booking.review.comment }}</p><p v-if="booking.review.vendor_reply" class="taxi-note"><strong>{{ t('common.vendor_reply', 'Vendor reply') }}:</strong> {{ booking.review.vendor_reply }}</p></div><Link v-else :href="appUrl(`/account/taxi/reviews/create/${booking.id}`)" class="btn btn-svtp">{{ t('common.write_review', 'Write review') }}</Link></section>
            </main><aside class="taxi-detail-sidebar"><div class="taxi-action-card"><h2>{{ t('common.next_steps', 'Next steps') }}</h2><p v-if="actions.can_track" class="taxi-muted">{{ t('common.tracking_link_available', 'A customer tracking link is available for this booking.') }}</p><p v-else class="taxi-muted">{{ t('common.tracking_not_available', 'Live tracking is not available for this booking yet.') }}</p><button v-if="actions.can_cancel" type="button" class="btn btn-outline-danger w-100" data-bs-toggle="modal" data-bs-target="#taxi-cancel-modal">{{ t('common.cancel_booking', 'Cancel booking') }}</button><button v-if="actions.can_reschedule" type="button" class="btn btn-outline-svtp w-100 mt-2" data-bs-toggle="modal" data-bs-target="#taxi-reschedule-modal">{{ t('common.reschedule_booking', 'Reschedule booking') }}</button><p class="taxi-muted mt-3 mb-0">{{ t('common.taxi_no_driver_promise', 'Driver details and live location appear only when the booking state permits them.') }}</p></div><div class="taxi-action-card"><h2>{{ t('common.timestamps', 'Timestamps') }}</h2><dl><div v-for="(value, key) in booking.timestamps" :key="key" v-show="value"><dt>{{ label(key) }}</dt><dd>{{ date(value) }}</dd></div></dl></div></aside></div>
        </div>
        <div v-if="actions.can_cancel" id="taxi-cancel-modal" class="modal fade" tabindex="-1" aria-labelledby="taxi-cancel-label" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form @submit.prevent="cancellationForm.post(`${endpoint}/cancel`)"><div class="modal-header"><h2 id="taxi-cancel-label" class="modal-title">{{ t('common.cancel_booking', 'Cancel booking') }}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><p>{{ t('common.cancellation_request_note', 'The final cancellation fee and refund amount are calculated by the booking service.') }}</p><select v-model="cancellationForm.reason_code" class="form-select mb-3"><option v-for="reason in reasons" :key="reason" :value="reason">{{ label(reason) }}</option></select><textarea v-model="cancellationForm.reason" class="form-control" maxlength="500" required :placeholder="t('common.cancellation_reason', 'Cancellation reason')"></textarea><label class="d-flex gap-2 mt-3"><input v-model="cancellationForm.confirmed" type="checkbox" required /> {{ t('common.confirm_cancellation', 'I confirm this cancellation request.') }}</label><p v-if="cancellationForm.errors.booking || cancellationForm.errors.reason" class="taxi-error">{{ cancellationForm.errors.booking || cancellationForm.errors.reason }}</p></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">{{ t('common.close', 'Close') }}</button><button class="btn btn-danger" :disabled="cancellationForm.processing || !cancellationForm.confirmed">{{ t('common.confirm_cancellation', 'Confirm cancellation') }}</button></div></form></div></div></div>
        <div v-if="actions.can_reschedule" id="taxi-reschedule-modal" class="modal fade" tabindex="-1" aria-labelledby="taxi-reschedule-label" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form @submit.prevent="rescheduleForm.post(`${endpoint}/reschedule`)"><div class="modal-header"><h2 id="taxi-reschedule-label" class="modal-title">{{ t('common.reschedule_booking', 'Reschedule booking') }}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><p class="taxi-muted">{{ t('common.reschedule_price_note', 'The existing agreed price is preserved by the rescheduling service.') }}</p><label class="form-label" for="taxi-new-pickup">{{ t('common.pickup_time', 'Pickup date and time') }}</label><input id="taxi-new-pickup" v-model="rescheduleForm.pickup_at" type="datetime-local" required class="form-control mb-3" /><label class="form-label" for="taxi-reschedule-reason">{{ t('common.reason', 'Reason') }}</label><textarea id="taxi-reschedule-reason" v-model="rescheduleForm.reason" required maxlength="500" class="form-control" @blur="preview('reschedule')"></textarea><div v-if="rescheduleQuote" class="taxi-preview mt-3">{{ rescheduleQuote.pricing_impact }} · {{ label(rescheduleQuote.assignment_impact) }}</div><p v-if="error" class="taxi-error mt-2">{{ error }}</p><label class="d-flex gap-2 mt-3"><input v-model="rescheduleForm.confirmed" type="checkbox" required /> {{ t('common.confirm_reschedule', 'I confirm the new pickup time.') }}</label></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">{{ t('common.close', 'Close') }}</button><button class="btn btn-svtp" :disabled="rescheduleForm.processing || previewing || !rescheduleForm.confirmed">{{ t('common.confirm_reschedule', 'Confirm reschedule') }}</button></div></form></div></div></div>
    </AppLayout>
</template>
