<script setup>
import { computed, ref } from 'vue';
import { router, useForm } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import VendorLayout from '../../../Layouts/VendorLayout.vue';
import Pagination from '../../../Components/Pagination.vue';
import { appUrl } from '../../../appUrl';
const props = defineProps({ portal: String, policies: Object, vendors: Array, tripTypes: Array, settings: Object, canManage: Boolean, canSettings: Boolean });
const layout = computed(() => props.portal === 'admin' ? AdminLayout : VendorLayout);
const endpoint = appUrl(`/${props.portal}/taxi/cancellation-policies`);
const editing = ref(null);
const defaults = { name: '', vendor_profile_id: '', trip_type: '', currency: 'INR', is_active: true, effective_from: '', effective_until: '', free_cancel_before_minutes: '', fee_type: 'fixed', fee_value: 0, no_show_fee_type: 'fixed', no_show_fee_value: 0, minimum_fee: 0, maximum_fee: '' };
const form = useForm({ ...defaults });
const settingsForm = useForm({ ...props.settings });
function edit(policy) { editing.value = policy.id; for (const key of Object.keys(defaults)) form[key] = key.startsWith('effective_') ? (policy[key]?.slice(0,10) ?? '') : (policy[key] ?? ''); }
function save() { editing.value ? form.put(`${endpoint}/${editing.value}`) : form.post(endpoint); }
</script>
<template><component :is="layout"><div class="py-3"><h2>Taxi cancellation policies</h2><p class="text-muted">Vendor + trip type → vendor default → platform + trip type → platform default. Newest matching policy wins ties. Without a matching policy, cancellation has no fee. Currency must match.</p>
 <div class="card table-responsive mb-3"><table class="table mb-0"><thead><tr><th>Policy</th><th>Scope</th><th>Fee</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="policy in policies.data" :key="policy.id"><td>{{ policy.name }}</td><td>{{ policy.vendor_profile_id ? `Vendor ${policy.vendor_profile_id}` : 'Platform' }} / {{ policy.trip_type ?? 'All trips' }}</td><td>{{ policy.currency }} · {{ policy.fee_type }} · {{ policy.fee_value }}</td><td>{{ policy.is_active ? 'Active' : 'Inactive' }}</td><td><div v-if="canManage" class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" @click="edit(policy)">Edit</button><button class="btn btn-sm btn-outline-warning" @click="router.patch(`${endpoint}/${policy.id}/toggle`)">{{ policy.is_active ? 'Deactivate' : 'Activate' }}</button></div></td></tr><tr v-if="!policies.data.length"><td colspan="5">No policies configured.</td></tr></tbody></table><Pagination :links="policies.links" /></div>
 <form v-if="canManage" class="card p-3 mb-3" @submit.prevent="save"><h4>{{ editing ? 'Edit' : 'Create' }} policy</h4><div v-for="(error,key) in form.errors" :key="key" class="text-danger">{{ error }}</div><div class="row g-3">
 <div class="col-md-6"><label for="policy-name" class="form-label">Name</label><input id="policy-name" v-model="form.name" required class="form-control" /></div><div class="col-md-3"><label for="policy-currency" class="form-label">Currency</label><input id="policy-currency" v-model="form.currency" required maxlength="3" class="form-control" /></div>
 <div v-if="portal === 'admin'" class="col-md-3"><label for="policy-vendor" class="form-label">Vendor</label><select id="policy-vendor" v-model="form.vendor_profile_id" class="form-select"><option value="">Platform</option><option v-for="vendor in vendors" :key="vendor.id" :value="vendor.id">{{ vendor.business_name }}</option></select></div>
 <div class="col-md-4"><label for="policy-trip" class="form-label">Trip type</label><select id="policy-trip" v-model="form.trip_type" class="form-select"><option value="">All trips</option><option v-for="type in tripTypes" :key="type.value" :value="type.value">{{ type.label }}</option></select></div>
 <div v-for="field in [['fee_type','Cancellation fee type'],['no_show_fee_type','No-show fee type']]" :key="field[0]" class="col-md-4"><label :for="field[0]" class="form-label">{{ field[1] }}</label><select :id="field[0]" v-model="form[field[0]]" class="form-select"><option value="fixed">Fixed</option><option value="percentage">Percentage of booking total</option><option value="non_refundable">Non-refundable</option></select></div>
 <div v-for="field in [['free_cancel_before_minutes','Free cutoff (minutes; blank disables)'],['fee_value','Cancellation fee value'],['no_show_fee_value','No-show fee value'],['minimum_fee','Minimum fee'],['maximum_fee','Maximum fee (optional)']]" :key="field[0]" class="col-md-4"><label :for="field[0]" class="form-label">{{ field[1] }}</label><input :id="field[0]" v-model="form[field[0]]" type="number" min="0" :step="field[0] === 'free_cancel_before_minutes' ? '1' : '0.01'" class="form-control" /></div>
 <div v-for="field in ['effective_from','effective_until']" :key="field" class="col-md-4"><label :for="field" class="form-label">{{ field.replaceAll('_',' ') }}</label><input :id="field" v-model="form[field]" type="date" class="form-control" /></div><div class="col-12"><label><input v-model="form.is_active" type="checkbox" /> Active</label></div></div><div class="d-flex gap-2 mt-3"><button class="btn btn-svtp" :disabled="form.processing">Save policy</button><button type="button" class="btn btn-outline-secondary" @click="editing = null; form.reset()">New policy</button></div></form>
 <form v-if="canSettings" class="card p-3" @submit.prevent="settingsForm.put(appUrl('/admin/taxi/cancellation-settings'))"><h4>Cancellation and reschedule settings</h4><div v-for="(error,key) in settingsForm.errors" :key="key" class="text-danger">{{ error }}</div><label v-for="key in Object.keys(settings)" :key="key" class="d-block mb-2"><input v-model="settingsForm[key]" type="checkbox" /> {{ key.replaceAll('_',' ') }}</label><button class="btn btn-svtp align-self-start" :disabled="settingsForm.processing">Save settings</button></form>
</div></component></template>
