<script setup>
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import { Link, router } from '@inertiajs/vue3';
import { appUrl } from '../../../appUrl';
const props = defineProps({ properties: Array, propertyId: Number, dashboard: Object });
function select(event) { router.get(appUrl('/admin/hotel/operations'), { property_id: event.target.value || undefined, date: props.dashboard.date }, { preserveState: true }); }
function changeStatus(row, status) { router.patch(row.status_url, { status }, { preserveScroll: true }); }
</script>
<template><AdminLayout><div class="container-fluid py-3"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h3 mb-1">Hotel Operations</h1><p class="text-muted mb-0">Cross-property operational oversight for {{ dashboard.date }}.</p></div><select class="form-select" style="max-width: 280px" @change="select"><option value="">All properties</option><option v-for="property in properties" :key="property.id" :value="property.id" :selected="property.id === propertyId">{{ property.name }}</option></select></div><div class="row g-3 mb-4"><div v-for="(value, label) in { Arrivals: dashboard.kpis.arrivals, Departures: dashboard.kpis.departures, 'In-house': dashboard.kpis.in_house, Upcoming: dashboard.kpis.upcoming, Attention: dashboard.kpis.attention, Occupancy: `${dashboard.kpis.occupancy}%` }" :key="label" class="col-6 col-xl-2"><div class="card"><div class="card-body"><div class="small text-muted">{{ label }}</div><div class="fs-3 fw-semibold">{{ value }}</div></div></div></div></div><div v-for="section in [{ title: 'Attention required', rows: dashboard.attention }, { title: 'Arrivals', rows: dashboard.arrivals }, { title: 'Departures', rows: dashboard.departures }, { title: 'In-house', rows: dashboard.in_house }]" :key="section.title" class="card mb-3"><div class="card-header fw-semibold">{{ section.title }}</div><div v-if="!section.rows.length" class="card-body text-muted">Nothing requiring attention.</div><div v-else class="table-responsive"><table class="table table-hover mb-0"><tbody><tr v-for="row in section.rows" :key="row.id"><td><Link :href="row.url">{{ row.booking_number }}</Link></td><td>{{ row.guest_name }}</td><td>{{ row.property }}</td><td>{{ row.check_in }} → {{ row.check_out }}</td><td>{{ row.status }}</td><td>{{ row.payment_status }}</td><td><button v-for="(label, status) in row.status_actions" :key="status" class="btn btn-sm btn-outline-primary me-1" @click="changeStatus(row, status)">{{ label }}</button><Link class="btn btn-sm btn-outline-secondary" :href="row.url">View</Link></td></tr></tbody></table></div></div><div class="card"><div class="card-header fw-semibold">Room availability summary</div><div class="table-responsive"><table class="table mb-0"><tbody><tr v-for="room in dashboard.rooms" :key="`${room.property}-${room.room_type}`"><td>{{ room.property }}</td><td>{{ room.room_type }}</td><td>{{ room.capacity }}</td><td>{{ room.reserved }}</td><td>{{ room.available }}</td><td>{{ room.stop_sell ? 'Stop sell' : 'Open' }}</td></tr></tbody></table></div></div></div></AdminLayout></template>
