<script setup>
import { useForm } from '@inertiajs/vue3';
import AdminLayout from '../../../../Layouts/AdminLayout.vue';
import { appUrl } from '../../../../appUrl';
defineProps({ properties: Array, rooms: Array, plans: Array, customers: Array });
const form = useForm({ user_id: '', room_type_id: '', rate_plan_id: '', check_in: '', check_out: '', rooms: 1, adults: 2, children: 0, guest_name: '', guest_email: '', guest_phone: '', special_requests: '' });
function submit() { form.post(appUrl('/admin/hotel/bookings')); }
</script>
<template><AdminLayout><div class="container-fluid py-4"><h1>Create hotel booking</h1><form class="card p-4" @submit.prevent="submit"><div class="row g-2"><div class="col-md-6"><select v-model="form.room_type_id" class="form-select"><option value="">Property / room</option><option v-for="room in rooms" :key="room.id" :value="room.id">{{ room.name }} ({{ room.property?.name ?? room.property_id }})</option></select></div><div class="col-md-6"><select v-model="form.rate_plan_id" class="form-select"><option value="">Rate plan</option><option v-for="plan in plans" :key="plan.id" :value="plan.id">{{ plan.name }}</option></select></div><div class="col-md-3"><input v-model="form.check_in" type="date" class="form-control" /></div><div class="col-md-3"><input v-model="form.check_out" type="date" class="form-control" /></div><div class="col-md-2"><input v-model="form.rooms" type="number" min="1" class="form-control" placeholder="Rooms" /></div><div class="col-md-2"><input v-model="form.adults" type="number" min="1" class="form-control" placeholder="Adults" /></div><div class="col-md-2"><input v-model="form.children" type="number" min="0" class="form-control" placeholder="Children" /></div><div class="col-md-6"><input v-model="form.guest_name" class="form-control" placeholder="Guest name" /></div><div class="col-md-3"><input v-model="form.guest_email" type="email" class="form-control" placeholder="Email" /></div><div class="col-md-3"><input v-model="form.guest_phone" class="form-control" placeholder="Phone" /></div><div class="col-12"><textarea v-model="form.special_requests" class="form-control" placeholder="Special requests"></textarea></div></div><button class="btn btn-primary mt-3" :disabled="form.processing">Create booking</button></form></div></AdminLayout></template>
