<script setup>
import { Link } from '@inertiajs/vue3';
import AdminLayout from '../../../../Layouts/AdminLayout.vue';
import { appUrl } from '../../../../appUrl';
defineProps({ bookings: Object, statuses: Array, paymentStatuses: Array, properties: Array, vendors: Array });
const query = new URLSearchParams(window.location.search);
const filter = Object.fromEntries(['booking_number', 'customer', 'property_id', 'vendor_profile_id', 'status', 'payment_status', 'check_in_from', 'check_in_to', 'created_from', 'created_to'].map((key) => [key, query.get(key) || '']));
function applyFilters() { window.location.href = `${appUrl('/admin/hotel/bookings')}?${new URLSearchParams(Object.entries(filter).filter(([, value]) => value)).toString()}`; }
</script>
<template><AdminLayout><div class="container-fluid py-4"><div class="d-flex justify-content-between mb-3"><h1>Hotel Bookings</h1><Link class="btn btn-primary" :href="appUrl('/admin/hotel/bookings/create')">Create booking</Link></div><form class="card card-body mb-3" @submit.prevent="applyFilters"><div class="row g-2"><div class="col-md-2"><input v-model="filter.booking_number" class="form-control" placeholder="Booking number" /></div><div class="col-md-3"><input v-model="filter.customer" class="form-control" placeholder="Guest, email or phone" /></div><div class="col-md-2"><select v-model="filter.property_id" class="form-select"><option value="">All properties</option><option v-for="property in properties" :key="property.id" :value="property.id">{{ property.name }}</option></select></div><div class="col-md-2"><select v-model="filter.vendor_profile_id" class="form-select"><option value="">All vendors</option><option v-for="vendor in vendors" :key="vendor.id" :value="vendor.id">{{ vendor.business_name }}</option></select></div><div class="col-md-1"><select v-model="filter.status" class="form-select"><option value="">Status</option><option v-for="status in statuses" :key="status.value" :value="status.value">{{ status.label }}</option></select></div><div class="col-md-2"><select v-model="filter.payment_status" class="form-select"><option value="">Payment</option><option v-for="status in paymentStatuses" :key="status.value" :value="status.value">{{ status.label }}</option></select></div><div class="col-md-2"><input v-model="filter.check_in_from" type="date" class="form-control" /></div><div class="col-md-2"><input v-model="filter.check_in_to" type="date" class="form-control" /></div><div class="col-md-2"><input v-model="filter.created_from" type="date" class="form-control" /></div><div class="col-md-2"><input v-model="filter.created_to" type="date" class="form-control" /></div><div class="col-md-2"><button class="btn btn-outline-primary">Apply</button><a class="btn btn-link" :href="appUrl('/admin/hotel/bookings')">Clear</a></div></div></form><div class="table-responsive"><table class="table"><thead><tr><th>Reference</th><th>Property / vendor</th><th>Guest</th><th>Dates</th><th>Status</th><th>Payment</th><th>Total</th></tr></thead><tbody><tr v-for="booking in bookings.data" :key="booking.id"><td><Link :href="appUrl(`/admin/hotel/bookings/${booking.id}`)">{{ booking.booking_number }}</Link></td><td>{{ booking.property?.name ?? booking.property_name_snapshot }}<br><small>{{ booking.vendorProfile?.business_name ?? 'Platform' }}</small></td><td>{{ booking.guest_name }}<br><small>{{ booking.guest_email }}</small></td><td>{{ booking.check_in }} → {{ booking.check_out }}</td><td>{{ booking.status }}</td><td>{{ booking.payment_status }}</td><td>{{ booking.currency }} {{ booking.total }}</td></tr></tbody></table></div></div></AdminLayout></template>
