<script setup>
import axios from 'axios';
import { ref } from 'vue';
import { useForm, Link } from '@inertiajs/vue3';
import AdminLayout from '../../../../Layouts/AdminLayout.vue';
import { appUrl } from '../../../../appUrl';
const props = defineProps({ booking: Object, timeline: Array, cancellationQuote: Object });
const statusForm = useForm({ status: props.booking.status });
const cancelForm = useForm({ idempotency_key: 'admin-cancel-' + props.booking.id, reason_code: 'other' });
const refundForm = useForm({ idempotency_key: 'admin-refund-' + props.booking.id });
const dateForm = useForm({ check_in: props.booking.check_in, check_out: props.booking.check_out, quote_fingerprint: '', idempotency_key: 'admin-reschedule-' + props.booking.id });
const quote = ref(null);
const endpoint = '/admin/hotel/bookings/' + props.booking.id;
function save() { statusForm.patch(appUrl(endpoint + '/status')); }
function cancel() { if (window.confirm('Cancel this booking?')) cancelForm.post(appUrl(endpoint + '/cancel')); }
function refund() { refundForm.post(appUrl(endpoint + '/refunds')); }
async function getQuote() { quote.value = (await axios.post(appUrl(endpoint + '/reschedule-quote'), { check_in: dateForm.check_in, check_out: dateForm.check_out })).data; }
function reschedule() { dateForm.quote_fingerprint = quote.value.quote_fingerprint; dateForm.post(appUrl(endpoint + '/reschedule')); }
</script>
<template><AdminLayout><div class="container-fluid py-4"><Link :href="appUrl('/admin/hotel/bookings')">← Hotel bookings</Link><h1 class="mt-3">{{ booking.booking_number }}</h1><div class="card p-4"><p><strong>Booking status:</strong> {{ booking.status }} · <strong>Payment status:</strong> {{ booking.payment_status }}</p><p>{{ booking.check_in }} → {{ booking.check_out }} · {{ booking.currency }} {{ booking.total }}</p><select v-model="statusForm.status" class="form-select mb-2"><option v-for="value in ['pending','confirmed','checked_in','checked_out','completed','cancelled','no_show']" :key="value">{{ value }}</option></select><button class="btn btn-primary" @click="save">Update status</button></div><div class="card p-4 mt-3"><h4>Cancellation and refunds</h4><p>Eligibility: {{ cancellationQuote.eligible ? 'Eligible' : 'Unavailable' }} · Fee: {{ booking.currency }} {{ cancellationQuote.cancellation_fee }} · Refundable: {{ booking.currency }} {{ cancellationQuote.remaining_refundable }}</p><p class="small text-muted">{{ cancellationQuote.policy_summary.summary || cancellationQuote.policy_summary.mode }}</p><button v-if="cancellationQuote.eligible" class="btn btn-outline-danger me-2" @click="cancel">Cancel booking</button><button v-if="cancellationQuote.remaining_refundable > 0" class="btn btn-outline-primary" @click="refund">Create refund record</button><div v-for="item in booking.hotel_refunds" :key="item.id" class="small mt-2">{{ item.refund_number }} · {{ item.amount }} · Refund {{ item.status }}</div></div><div v-if="['pending','confirmed'].includes(booking.status)" class="card p-4 mt-3"><h4>Reschedule</h4><div class="row g-2"><div class="col-sm-5"><input v-model="dateForm.check_in" type="date" class="form-control"></div><div class="col-sm-5"><input v-model="dateForm.check_out" type="date" class="form-control"></div><div class="col-sm-2"><button class="btn btn-outline-primary w-100" @click="getQuote">Quote</button></div></div><div v-if="quote" class="mt-3"><p>New total: {{ booking.currency }} {{ quote.new_total }} · Difference: {{ booking.currency }} {{ quote.difference }}</p><p v-if="quote.difference > 0">Additional amount due: {{ booking.currency }} {{ quote.additional_payment_due }}</p><p v-else-if="quote.difference < 0">Potential refund: {{ booking.currency }} {{ quote.refundable_difference }}</p><button v-if="quote.eligible" class="btn btn-primary" @click="reschedule">Confirm reschedule</button></div></div><div class="card p-4 mt-3"><h4>History and timeline</h4><div v-for="change in booking.changes" :key="change.id" class="small border-bottom py-2">{{ change.old_check_in }} → {{ change.new_check_in }} · {{ change.old_total }} → {{ change.new_total }}</div><div v-for="entry in timeline" :key="entry.event + entry.created_at" class="small border-bottom py-2">{{ entry.description }} <span class="text-muted">{{ entry.created_at }}</span></div></div></div></AdminLayout></template>
